# Generated by Django 4.2.10 on 2024-02-14 18:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('data_nascimento', models.DateField(default=django.utils.timezone.now)),
                ('genero', models.CharField(choices=[('na', 'Não informado'), ('homem-cis', 'Homem cis'), ('homem-trans', 'Homem trans'), ('mulher-cis', 'Mulher cis'), ('mulher-trans', 'Mulher trans'), ('nao-binario', 'Não-binário'), ('outro', 'Outro')], default='na', max_length=20)),
                ('profissao', models.CharField(default='Não informada', max_length=200)),
                ('endereco', models.CharField(default='Não informado', max_length=200)),
                ('telefone', models.CharField(default='Não informado', max_length=20)),
                ('peso', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('tipo_sanguineo', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('na', 'Não informado/Não sabe')], default='na', max_length=4)),
                ('fumo_alcool', models.CharField(choices=[('n', 'Não'), ('d', 'Diariamente'), ('s', 'Semanalmente'), ('m', 'Mensalmente'), ('a', 'Anualmente')], default='n', max_length=200)),
                ('exercicio', models.CharField(default='Nâo informado', max_length=200)),
                ('exercicio_frequencia', models.CharField(choices=[('n', 'Não'), ('d', 'Diariamente'), ('s', 'Semanalmente'), ('m', 'Mensalmente'), ('a', 'Anualmente')], default='n', max_length=200)),
            ],
            options={
                'verbose_name': 'dados',
                'verbose_name_plural': 'Dados',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('cnes', models.CharField(default='0000000', editable=False, max_length=7, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=150)),
                ('cep', models.CharField(max_length=20)),
                ('categoria', models.CharField(choices=[('HOSPITAL_PUBLICO', 'Público'), ('HOSPITAL_PRIVADO', 'Privado'), ('HOSPITAL_FILANTROPICO', 'Filantrópico')], default='', max_length=100)),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espirito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'Sâo Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='', max_length=100)),
                ('municipio', models.CharField(default='', max_length=150)),
                ('telefone', models.CharField(default='Não informado', max_length=100)),
                ('email', models.CharField(default='Não informado', max_length=100)),
                ('tempo_emergente', models.IntegerField(default=0)),
                ('tempo_muito_urgente', models.IntegerField(default=0)),
                ('tempo_urgente', models.IntegerField(default=0)),
                ('tempo_pouco_urgente', models.IntegerField(default=0)),
                ('tempo_nao_urgente', models.IntegerField(default=0)),
                ('nota', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('leitos', models.IntegerField(default=0)),
                ('uti_adulto', models.IntegerField(default=0)),
                ('uti_pediatrico', models.IntegerField(default=0)),
                ('uti_neonatal', models.IntegerField(default=0)),
                ('uti_queimado', models.IntegerField(default=0)),
                ('atualizacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Hospitais',
            },
        ),
        migrations.CreateModel(
            name='Sintomas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sintoma', models.CharField(default='N/A', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sintomas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1', 'Medicamento com prescrição'), ('2', 'Medicamento sem prescrição')], default='1', max_length=200)),
                ('medicamento', models.CharField(default='N/A', max_length=200)),
                ('frequencia', models.CharField(choices=[('n', 'Não'), ('d', 'Diariamente'), ('s', 'Semanalmente'), ('m', 'Mensalmente'), ('a', 'Anualmente')], default='n', max_length=200)),
                ('numero_frequencia', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Internacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internacao', models.CharField(default='N/A', max_length=200)),
                ('tempo', models.IntegerField(default=0)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internacoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doencas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doenca', models.CharField(default='N/A', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doencas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'doença',
                'verbose_name_plural': 'Doenças',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.CharField(default='N/A', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Condicao_familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicao', models.CharField(default='N/A', max_length=200)),
                ('grau_parentesco', models.CharField(choices=[('1', '1° Grau'), ('2', '2° Grau'), ('3', '3° Grau')], default='1', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condicao_familiar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cirurgia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cirurgia', models.CharField(default='N/A', max_length=200)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cirurgias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(default='', max_length=100)),
                ('numero', models.IntegerField(default=1)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('risco', models.CharField(choices=[('EMERGENTE', 'Emergente'), ('MUITO_URGENTE', 'Muito Urgente'), ('URGENTE', 'Urgente'), ('POUCO_URGENTE', 'Pouco Urgente'), ('NAO_URGENTE', 'Não Urgente')], default='NAO_URGENTE', max_length=100)),
                ('horario_entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('horario_atendimento', models.DateTimeField(default=django.utils.timezone.now)),
                ('horario_saida', models.DateTimeField(default=django.utils.timezone.now)),
                ('duracao', models.DurationField(default=datetime.timedelta(seconds=1800))),
                ('avaliacao', models.IntegerField(default=3)),
                ('observacao', models.TextField(default='')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medconnect.hospital')),
            ],
            options={
                'verbose_name': 'avaliação',
                'verbose_name_plural': 'Avaliações',
            },
        ),
    ]
